# Generated by Django 3.1.2 on 2020-11-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='edad',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
